### ISSUE TITLE
Idea: Baseless unittests

### ISSUE THREAD

**Issue by thekid** [xp-framework/unittest#15]
## Is this a good idea?

<table><tr><td width="360" valign="top">
Writing this:
<pre lang="php">
use function unittest\skip;
use function unittest\fail;
use function unittest\assertEquals;

class ExampleTest {

  #[@test]
  public function skipped() {
    skip('Because I can');
  }

  #[@test]
  public function fails() {
    fail('Because I do');
  }

  #[@test]
  public function succeeds() {
    assertEquals(1, 1);
  }
}
</pre>
</td><td width="360" valign="top">
...instead of:
<pre lang="php">
use unittest\TestCase;

class ExampleTest extends TestCase {

  #[@test]
  public function skipped() {
    $this->skip('Because I can');
  }

  #[@test]
  public function fails() {
    $this->fail('Because I do');
  }

  #[@test]
  public function succeeds() {
    $this->assertEquals(1, 1);
  }
}
</pre>
</td></tr></table>

Unsure whether the left-hand side really has any benefits. /cc @mikey179 - you've been doing this recently, what are your experiences and thoughts?

**Comment by mikey179** [comment]
I've switched assertions and the fail functionality only, but not the tests themselves yet. For assertions I think it is nice when you can see all types of assertions on top of the file, it gives an overview of what is really being used. Also, it makes the tests itself more clean, as they are not convoluted with `$this->` which adds nothing to the meaning of the test and is just technical noise. 

Regarding the tests itself, I think there is no technical reason any more that they must be written in a certain way, i.e. that they must extend a certain class in order to be executeable. I believe everything that can be left away to get down to the pure functionality and what should be really expressed is always better.

**Comment by thekid** [comment]
After a discussion on this topic we had, removing the requirement to extend a base class has the following benefits:
- I do not inherit functionality I don't want to. Interesting if I wanted to use a different assertion library than the one built in, e.g. https://github.com/xp-forge/assert
- I don't have to watch out when I overwrite the constructor. Currently `parent::__construct($name)` needs to be called, or else the test won't work as expected!
- I can also have a test method named `getName()`. OK, small benefit only.

**Comment by thekid** [comment]
Another idea could be to solve this with traits. The benefit would be that autoloading kicks in and we can only load the assertion library that we want to.

<table><tr><td width="360" valign="top">
Writing this:
<pre lang="php">
use unittest\Assertions;
class ExampleTest {
  use Assertions;
  #[@test]
  public function skipped() {
    $this->skip('Because I can');
  }
  #[@test]
  public function fails() {
    $this->fail('Because I do');
  }
  #[@test]
  public function succeeds() {
    $this->assertEquals(1, 1);
  }
}
</pre>
</td><td width="360" valign="top">
...instead of:
<pre lang="php">
use unittest\TestCase;
class ExampleTest extends TestCase {
  #[@test]
  public function skipped() {
    $this->skip('Because I can');
  }
  #[@test]
  public function fails() {
    $this->fail('Because I do');
  }
  #[@test]
  public function succeeds() {
    $this->assertEquals(1, 1);
  }
}
</pre>
</td></tr></table>

**Comment by thekid** [comment]
See #36
